Repository SmartCourse/app, pull requests merged in 2018-09, with the labels that each got.

#118 Rework to allow for dynamic actions in Vuex store
  .gitignore
  .travis.yml
  backend/.eslintrc.js
  backend/package-lock.json
  backend/public/css/app.34b52ddf.css
  backend/public/css/chunk-7c90.5005d564.css
  backend/public/index.html
  backend/public/js/app.9efc53c3.js
  backend/public/js/app.9efc53c3.js.map
  backend/public/js/chunk-7c90.46ecf08e.js
  backend/public/js/chunk-7c90.46ecf08e.js.map
  backend/public/js/chunk-vendors.b476a1f4.js
  backend/public/js/chunk-vendors.b476a1f4.js.map
  backend/public/js/f820.cd19a448.js
  backend/public/js/f820.cd19a448.js.map
  backend/src/index.js
  backend/src/models/db.js
  frontend/.eslintrc.js
  frontend/package-lock.json
  frontend/public/index.html
  frontend/src/store/questions/constants.js
  frontend/src/store/questions/index.js
  frontend/src/utils/api/index.js
  frontend/src/utils/api/questions.js
  frontend/src/views/Home.vue
  frontend/src/views/Question.vue
Labels: chore

#119 S3 design streamlining
  .travis.yml
  backend/src/index.js
  backend/src/utils/cors.js
  docs/styles-faq.md
  frontend/data/feed.json
  frontend/data/questions/1.json
  frontend/src/App.vue
  frontend/src/components/AnswerForm.vue
  frontend/src/components/AppButton.vue
  frontend/src/components/AppFooter.vue
  frontend/src/components/AppLogo.vue
  frontend/src/components/AppNavBar.vue
  frontend/src/components/Card.vue
  frontend/src/components/Feed.vue
  frontend/src/components/questions-answers/AnswerCard.vue
  frontend/src/components/questions-answers/AnswerForm.vue
  frontend/src/components/questions-answers/QuestionCard.vue
  frontend/src/css/card.less
  frontend/src/main.js
  frontend/src/store/questions/index.js
  frontend/src/utils/api/questions.js
  frontend/src/views/Question.vue
  frontend/tests/unit/QuestionCard.spec.js
Labels: Task, feature

#122 S3 DB tests
  .gitignore
  backend/src/controllers/course.js
  backend/src/models/answer.js
  backend/src/models/course.js
  backend/src/models/db/index.js
  backend/src/models/db/tables.js
  backend/src/models/question.js
  backend/src/routes/course.js
  backend/tests/db/dbinstantiation.js
  backend/tests/routes/course.js
  backend/tests/routes/questions.js
  backend/tests/routes/uni.js
  frontend/src/App.vue
  frontend/src/components/AppFooter.vue
  frontend/src/components/AppNavBar.vue
  frontend/src/views/About.vue
Labels: chore

#124 Playing with tests
  backend/tests/routes/api.js
  backend/tests/routes/course.js
  backend/tests/routes/questions.js
Labels: chore

#132 Submission final plan
  backend/tests/routes/course.js
  docs/project-plan.md
Labels: High Priority

#133 S4 dependency injection models
  backend/src/controllers/course.js
  backend/src/controllers/question.js
  backend/src/models/answer.js
  backend/src/models/course.js
  backend/src/models/db/index.js
  backend/src/models/question.js
  backend/tests/db/dbinstantiation.js
  backend/tests/models/answer.js
  backend/tests/models/question.js
  backend/tests/models/stub-db.js
Labels: bug
