Repository SmartCourse/app, pull requests merged in 2018-08, with the labels that each got.

#6 Made some changes to Readme
  README.md
Labels: feature

#7 Created git workflow doc
  docs/git.md
Labels: feature

#8 Tech stack overview
  docs/technology.md
Labels: help wanted, question

#94 for luke
  backend/package-lock.json
  backend/package.json
  backend/src/bin/www
  backend/src/controllers/index.js
  tests/test.js
Labels: bug, chore

#103 S2 frontend restructure
  frontend/src/store/questions.js
  frontend/src/utils/api.js
  frontend/src/utils/api/index.js
  frontend/src/utils/api/questions.js
  frontend/tests/unit/Feed.spec.js
  frontend/tests/unit/QuestionCard.spec.js
  frontend/tests/unit/api/index.js
Labels: Task, chore

#101 Coverage now built into tests
  .gitignore
  .travis.yml
  README.md
  backend/.coveralls.yml
  backend/GemFile
  backend/package-lock.json
  backend/package.json
Labels: chore
