Repository SmartCourse/app, pull requests merged in 2019-02, with the labels that each got.

#340 authCV initialized to null, getter used in checkAuth
  backend/src/index.js
  frontend/.env
  frontend/.env.staging
  frontend/public/index.html
  frontend/src/store/auth/index.js
  frontend/vue.config.js
Labels: bug

#346 Bugfix: DATE -> DATETIME2 , sql columns were storing dates only!
  backend/scripts/db/init_sql.js
  backend/src/models/constants.js
  backend/src/models/db/config.js
Labels: bug

#345 Bugfix: Ratings fixes
  frontend/src/store/course/index.js
  frontend/src/views/course/index.vue
Labels: bug

#347 fixed course rating aggregation sql
  backend/src/models/course.js
Labels: bug

#357 Mobile Menu
  frontend/src/components/AppNavBar.vue
  frontend/src/components/Nav/MiniMenu.vue
Labels: feature

#365 Draft Feed
  public/index.html
  src/App.vue
  src/components/AppNavBar.vue
  src/components/Card/Border.vue
  src/components/Card/Small.vue
  src/components/Card/index.vue
  src/components/Category/Badge.vue
  src/components/Category/index.vue
  src/components/Course/FeedCard.vue
  src/components/Course/TabButton.vue
  src/components/Nav/SubNav/index.vue
  src/components/PromoTile/index.vue
  src/components/Search/index.vue
  src/components/User/Mini.vue
  src/router/course/index.js
  src/router/home/index.js
  src/router/routes.js
  src/store/root.js
  src/utils/helpers.js
  src/views/Feed.vue
  src/views/Home.vue
  src/views/HomeRoute.vue
  src/views/Profile.vue
  src/views/course/index.vue
Labels: High Priority
